### ISSUE TITLE
Opening project with eq_configurator

### ISSUE THREAD

**Issue by Michkt** [shawnbanasick/eq_configurator#1]
Hi.
I am not a programmer and am using q-mthodology to complete a research project.
I have followed the instructions provided to use easy htmlq version 2 to set up my research and when I get to the point where I want to test my project i get the following message.
"An error occured while opening your survey. Due to improved browser security measures, it is no longer possible to view these files by double clicking on index.html. To view and test your file setup, please use Easy HTMLQ Configurator."
I am not sure what I am doing wrong but would really appreciate somehelp with this. Please don't be afraid to use very simple instructions as this is not my field and i am not afraid to say that I don't understand a lot but can follow instructions.
Many thanks
Michelle

**Comment by shawnbanasick** [comment]
Hi Michelle,

This error usually happens when Easy HTMLQ can't find the settings files. Please check your "settings" folder in Easy HTMLQ and look to see if you have four files named:

config.xml
language.xml
map.xml
statements.xml

If you have changed any of the names of the files - for example to  new-config.xml or config1.xml - then this error will happen.  The names have to remain exactly as listed above. Renaming the files should fix the problem. 

If the file names are all OK and you are still getting the error, then upload your files to netlify (even with the error) and send the netlify url for your project to me at:

ken.q.tools@gmail.com

I'll be able to get a better sense of the problem then.
